LIBNAME D "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 76\REG";
RUN;
/*CHECKING WHETHER SUM OF % EDUCATION = 100 */
/*OR NOT*/
DATA D.A;SET D.ELEMAPI;
S=NOT_HSG+HSG+SOME_COL+COL_GRAD+GRAD_SCH;RUN;
PROC FREQ DATA = D.A;TABLES S;RUN;
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 73\REG\O.XLS";
PROC UNIVARIATE DATA = D.ELEMAPI 
NEXTROBS = 15;RUN;ODS HTML CLOSE;
ODS HTML FILE = "C:\OT\A.XLS";
PROC MEANS DATA = D.ELEMAPI MIN MAX
MEAN MEDIAN Q1 Q3 STD;RUN;ODS HTML CLOSE;
/*CHECKING WHETHER MISSING AVG ED AND SUM OF*/
/*% EDUCTIUON = 0 ARE FOR THE SAME SET*/
/*OF SCHOOLS*/
PROC FREQ DATA = D.A;TABLES S;
WHERE AVG_ED = .;RUN;
PROC FREQ DATA = D.A;TABLES AVG_ED ;
WHERE S=0;RUN;
/*CHECK IF FULL IS PROBLEM IN ANY PARTICULAR*/
/*DISTRICT OR NOT*/
PROC FREQ DATA = D.A;TABLES DNUM;
WHERE FULL <=1;RUN;
DATA D.A;SET D.A;
/*NEGATIVE TO +VE*/
ACS_K3 = ABS(ACS_K3);
/*MISSING VALUE TO 0*/
IF AVG_ED = . THEN AVG_ED = 0;
/*INVALID RATIOS TO %*/
IF FULL <=1 THEN FULL = FULL*100;
/*OUTLIERS*/
IF ENROLL > 1264 THEN ENROLL = 1264;RUN;
/*MISSING VALUES*/
PROC MEANS DATA = D.A MEAN NMISS;RUN;
PROC MEANS DATA = D.ELEMAPI 
MIN MAX MEAN NMISS;
VAR MEALS;CLASS MEALCAT;RUN;
/*MISSING VALUES REPLACED WITH MEANS*/
DATA D.A;SET D.A;
IF ACS_K3 = . THEN ACS_K3 =19.1608040;
IF ACS_46 = . THEN ACS_46 =29.6851385;
IF MOBILITY = . THEN MOBILITY =18.2531328;
IF MEALCAT = 1 AND MEALS = . THEN MEALS = 0;
IF MEALCAT = 2 AND MEALS = . THEN MEALS = 66.0468750;RUN;
/*FREQ FOR CATEGORY VARIABLES*/
PROC FREQ DATA = D.A;
TABLES MEALCAT YR_RND;RUN;
/*CORR WITH THE CONT VARIABLES*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 73\REG\O.XLS";
PROC CORR DATA = D.A;
WITH API00;RUN;ODS HTML CLOSE;
/*SIGN OK SIGNIFICANCE OK: KEEP IT*/
/*SIGN NOT OK SIGNIFICANCE NOT OK: DROP IT*/
/*SIGN NOT OK SIGNIFICANCE OK: DISCUSS*/
/*SIGN OK SIGNIFICANCE NOT OK: EXPLORE-SCATTER PLOT, IF RANDOM THEN IGNORE*/
/*ELSE TRY TRANSFORMATIONS.*/
/*MEAN TEST WITH CATEGORY VARIABLES*/
PROC MEANS DATA = D.A MEAN;VAR API00;
CLASS MEALCAT;RUN;
/*ANOVA TO CHECK SIGNIFICANCE*/
PROC ANOVA DATA = D.A;CLASS MEALCAT;
MODEL API00=MEALCAT;RUN;
PROC MEANS DATA = D.A MEAN;VAR API00;
CLASS YR_RND;RUN;
PROC MEANS DATA = D.A MEAN;VAR FULL AVG_ED MOBILITY MEALS;
CLASS YR_RND;RUN;
/*ANOVA TO CHECK SIGNIFICANCE*/
PROC ANOVA DATA = D.A;CLASS YR_RND;
MODEL API00=YR_RND;RUN;
/*Y = A+B1X1+B2X2+….+BKXK + U*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 73\REG\R.XLS";
PROC REG DATA = D.A;
MODEL API00 = 
meals
ell
yr_rnd
mobility
acs_k3
acs_46
not_hsg
hsg
some_col
col_grad
grad_sch
avg_ed
full
emer
enroll
mealcat
/VIF COLLIN;
RUN;
ODS HTML CLOSE;
/*ALPHA = 0.01%*/
/*VIF <=1.5(2), P <0.0001*/
/*R -SQUARE 65%*/

/*HOMOSCEDASTICITY - i.e. THE*/
/*VARIANCE OF THE ERROR COMPONENT */
/*MUST BE CONSTANT ACROSS THE CROSS SECTION*/
/*WHITE'S TEST*/
/*H0: MODEL IS HOMOSCEDASTIC*/
/*H1: MODEL IS HETEROSCEDASTIC;*/
/*P < ALPHA => HETEROSCEDASTICITY WHICH*/
/*CAN BE REDUCED BY TRANSFORMATION OF X*/
/*VARIABLES PARTICULARLY LOG OR SQUARE ROOT*/
/*SPEC*/
/*HETEROSCEDASTICITY*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SOUVIK SIR BATCH FILES\BATCH 73\REG\R.XLS";
PROC REG DATA = D.A;
MODEL API00 = 
/*meals*/
ell
/*yr_rnd*/
mobility
/*acs_k3*/
/*acs_46*/
/*not_hsg*/
/*hsg*/
/*some_col*/
/*col_grad*/
/*grad_sch*/
avg_ed
full
/*emer*/
/*enroll*/
/*mealcat*/
/SPEC;
RUN;
ODS HTML CLOSE;
/*CREATE THE OUTPUT FILE*/
PROC REG DATA = D.A;
MODEL API00 = 
/*meals*/
ell
/*yr_rnd*/
mobility
/*acs_k3*/
/*acs_46*/
/*not_hsg*/
/*hsg*/
/*some_col*/
/*col_grad*/
/*grad_sch*/
avg_ed
full
/*emer*/
/*enroll*/
/*mealcat*/
;
OUTPUT OUT = D.O 
P = PRED R = RES;RUN;QUIT;
/*NORMALITY OF RESIDUAL*/
PROC UNIVARIATE DATA = D.O NORMAL;
VAR RES;HISTOGRAM RES/NORMAL;RUN;

/*MAPE*/
/*MEAN ABSOLUTE PERCENTAGE ERROR*/
/*ERROR = ACTUAL - PREDICTED*/
/*ABS(ERROR/ACTUAL)*100*/
/*MEAN OF THE ABOVE = MAPE*/
DATA D.O;SET D.O;
ERROR = ABS(RES/API00)*100;RUN;
PROC MEANS DATA = D.O MEAN;VAR ERROR;RUN;
1. OVERALL SIGNIFICANCE P < ALPHA
2. MULTICOLLINEARITY - VIF <=1.5
3. INDIVIDUAL SIGNIFICANCE - P < ALPHA
4. HOMOSCEDASTICITY CHECK - P > ALPHA
5. NORMALITY CHECK - P > APLHA
6. MAPE <=10%
7. R - SQUARE >= 65%

1.	EXCEL FILE - VIF AND SPEC - R2 > 65%, 
VIF <=1.5(2), P < 0.0001, SPEC - P > 0.0001
2.	EXCEL FILE - UNIVARIATE WITH NORMAL - 
NORMAL P VALUE NOT SIGNIFICANT
3.	NORMAL GRAPH 
4.	MAPE - BELOW 10%
5.	DASHBOARD
6.	PPT ;
DATA D V;
SET SASHELP.AIR;
IF RANUNI(458712) <=0.6 THEN OUTPUT D;
ELSE OUTPUT V;RUN;
1. OBJECTIVE
2. OUTCOME - MAPE. R -SQUARE
3. CONCLUSION
4. STRATEGY
5. APPENDIX 
